hello/urls.py
from django.urls import path

from hello import views

app_name = 'hello'

urlpatterns = [
    path('', views.hello, name='home'),
]

mysite/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('polls/', include('polls.urls')),
                  path("", include('hello.urls')),
              ] + debug_toolbar_urls()

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:pk>/results", views.ResultView.as_view(), name="results"),
]

hello/models.py
# Create your models here.

polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published Recently",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

hello/views.py
from django.shortcuts import render


# Create your views here.
def hello(request):
    greetings = {
        "greetings": "Assalam-O-Alaikum World From Django."
    }
    return render(request, "start/index.html", greetings)

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    ...

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


# Create your views here.

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/question_detail.html",
                      {'question': question, 'error_message': "You didn't select any option."})
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=[question_id]))

hello/templates/start/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <title>Scrolling Nav - Start Bootstrap Template</title>
    <link href="{% static 'start/assets/favicon.ico' %}" rel="icon" type="image/x-icon"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'start/css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container px-4">
        <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                data-bs-target="#navbarResponsive" data-bs-toggle="collapse" type="button"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'hello:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'polls:home' %}">Poll App</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin App</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-primary bg-gradient text-white">
    <div class="container px-4 text-center">
        <h1 class="fw-bolder">
            {{ greetings }}
            <!--                    Welcome to Scrolling Nav-->
        </h1>
        <p class="lead">A functional Bootstrap 5 boilerplate for one page scrolling websites</p>
        <a class="btn btn-lg btn-light" href="#about">Start scrolling!</a>
    </div>
</header>
{% block 'main-content' %} {% endblock 'main-content' %}
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website
            <script>document.write(new Date().getFullYear());</script>
            - 2023
        </p>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'start/js/scripts.js' %}"></script>
</body>
</html>

hello/templates/start/index.html
{% extends 'start/base.html' %}
{% block 'main-content' %}
<!-- About section-->
<section id="about">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>About this page</h2>
                <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled
                    so you can use it as a boilerplate or starting point for you own landing page designs! This template
                    features:</p>
                <ul>
                    <li>Clickable nav links that smooth scroll to page sections</li>
                    <li>Responsive behavior when clicking nav links perfect for a one page website</li>
                    <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the
                        navbar
                    </li>
                    <li>Minimal custom CSS so you are free to explore your own unique design options</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- Services section-->
<section class="bg-light" id="services">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Services we offer</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore,
                    expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda
                    laborum vel, labore ut velit dignissimos.</p>
            </div>
        </div>
    </div>
</section>
<!-- Contact section-->
<section id="contact">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Contact us</h2>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem
                    dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa
                    exercitationem, in, quo totam.</p>
            </div>
        </div>
    </div>
</section>
{% endblock 'main-content' %}

polls/templates/polls/detail.html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
<h1>Question Details:</h1>
<form name="voteForm" action = "{% url 'polls:vote' question.id%}" method="POST">
    {% csrf_token %}
<p>{{ question.question_text }}</p>
    {% for choice in question.choice_set.all %}
    <input type="radio" value="{{ choice.id }}" name="choice"/>{{ choice.choice_text }}
    {% endfor %}
    <input type="submit" name="voteBTN" value="Vote"/>
</form>
</body>
</html>

polls/templates/polls/index.html
<!doctype html>
<html lang="en-US">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Document</title>
    <link href="{% static 'polls/assets/css/styles.css' %}" rel="stylesheet">
    <link href="{% static '/polls/assets/images/favicon.ico' %}" rel="icon" type="image/x-icon"/>
</head>
<body>
<h1>Question Lists</h1>
<div class="vote_image"></div>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No Question Found</p>
{% endif %}
<script src="{% static 'polls/assets/js/functions.js' %}"></script>
</body>
</html>

polls/templates/polls/question_detail.html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Document</title>
</head>
<body>
<h1>Question Details:</h1>
<form action="{% url 'polls:vote' question.id%}" method="POST" name="voteForm">
    {% csrf_token %}
    <p>{{ question.question_text }}</p>
    {% for choice in question.choice_set.all %}
    <input name="choice" type="radio" value="{{ choice.id }}"/>{{ choice.choice_text }}
    {% endfor %}
    <input name="voteBTN" type="submit" value="Vote"/>
</form>
</body>
</html>

polls/templates/polls/results.html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Document</title>
</head>
<body>
<h1>Question Details:</h1>
<p>{{ question.question_text }}</p>
<table class="">
    <tr>
        <th>Beverage</th>
        <th>Votes</th>
    </tr>
    {% for choice in question.choice_set.all %}
    <tr>
        <td>{{ choice.choice_text }}</td>
        <td>{{ choice.votes }}</td>
    </tr>
    {% endfor %}
</table>
<ul>
    <li><a href="{% url 'hello:home' %}">Home</a></li>
    <li><a href="{% url 'polls:home' %}">Polls</a></li>
</ul>
</body>
</html>